[package]
name = "cargo-dist-schema"
version = "0.2.2-prerelease7"
edition = "2021"
exclude = [
  "book/*",
  "src/snapshots/*",
  "src/tests/",
  "tests/",
]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camino = "1.1.1"
schemars = "0.8.11"
semver = "1.0.14"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"

[dev-dependencies]
insta = "1.26.0"
